version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket <bucketname> --output-template-file outputtemplate.yml # Change bucket name
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
